//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsArch.NET.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTR_FUNCTIONS
    {
        public int ID_ATTR { get; set; }
        public string STR_FILE { get; set; }
        public string STR_CLASS { get; set; }
        public string STR_FUNCTION { get; set; }
        public Nullable<int> ID_FUNCTION { get; set; }
    
        public virtual ATTR ATTR { get; set; }
    }
}
