//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsArch.NET.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTOREF
    {
        public int ID_ATTR { get; set; }
        public Nullable<int> ID_DEFAULTNODE { get; set; }
        public int ID_TYPEREF { get; set; }
        public Nullable<int> ID_COL { get; set; }
        public Nullable<int> ID_CHILDATTR { get; set; }
        public Nullable<int> INT_WIDTH { get; set; }
        public string STR_COL { get; set; }
        public int ID_KEY { get; set; }
    }
}
