//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsArch.NET.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATALOG_TYPES
    {
        public int ID_ITEMTYPE { get; set; }
        public Nullable<int> CATALOG_TYPE { get; set; }
        public string LABEL_NAME { get; set; }
    }
}
