//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsArch.NET.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATALOG_RULES
    {
        public int ID_ITEMTYPE { get; set; }
        public int N_ORDER { get; set; }
        public int FOLDER_TYPE { get; set; }
        public Nullable<bool> IS_ALF { get; set; }
        public string FOLDER_NAME { get; set; }
    }
}
