//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsArch.NET.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHILD_ATTRS
    {
        public int ID_TYPE { get; set; }
        public int ID_ATTR { get; set; }
        public int ID_REFATTR { get; set; }
        public int ID_PARENTATTR { get; set; }
        public Nullable<int> IS_NOCONNECT { get; set; }
    
        public virtual ATTR ATTR { get; set; }
        public virtual ATTR ATTR1 { get; set; }
        public virtual ATTR ATTR2 { get; set; }
        public virtual ITEMTYPE ITEMTYPE { get; set; }
    }
}
