//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsArch.NET.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENTRULE_CONDS
    {
        public int ID_NODEACTION { get; set; }
        public int N_ORDER { get; set; }
        public int ID_ATTR { get; set; }
        public string STR_VALUE { get; set; }
        public Nullable<int> MODE_COND { get; set; }
        public Nullable<int> INT_VALUE { get; set; }
        public Nullable<int> N_VALUE { get; set; }
        public Nullable<int> ANDOR_VALUE { get; set; }
        public Nullable<int> OP_COND { get; set; }
    
        public virtual EVENTRULE_ACTIONS EVENTRULE_ACTIONS { get; set; }
    }
}
