//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsArch.NET.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EVENT()
        {
            this.EVENTRULE_ACTIONS = new HashSet<EVENTRULE_ACTIONS>();
        }
    
        public int ID_EVENT { get; set; }
        public Nullable<int> ID_TYPE { get; set; }
        public Nullable<int> EVENT_TYPE { get; set; }
        public Nullable<int> EVENT_MODE { get; set; }
        public string STR_FILE { get; set; }
        public string STR_CLASS { get; set; }
        public string STR_FUNCTION { get; set; }
        public Nullable<int> ID_ATTR { get; set; }
    
        public virtual ATTR ATTR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVENTRULE_ACTIONS> EVENTRULE_ACTIONS { get; set; }
        public virtual ITEMTYPE ITEMTYPE { get; set; }
    }
}
