//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsArch.NET.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENTRULE_OBJECTS
    {
        public int ID_EVENT { get; set; }
        public int N_ORDER { get; set; }
        public Nullable<int> ID_TYPE { get; set; }
        public Nullable<int> N_PARENT { get; set; }
        public Nullable<int> ID_PARENT { get; set; }
        public Nullable<bool> IS_RECURSION { get; set; }
    
        public virtual ITEMTYPE ITEMTYPE { get; set; }
    }
}
