//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsArch.NET.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXTERNAL_LINKS
    {
        public int ID_NODE { get; set; }
        public int ID_ATTR { get; set; }
        public int N_ORDER { get; set; }
        public int ID_DBNODE { get; set; }
        public int ID_EXTERNALNODE { get; set; }
        public string STR_EXTERNALPATH { get; set; }
        public Nullable<int> ID_EXTERNALROOTNODE { get; set; }
    
        public virtual ATTR ATTR { get; set; }
        public virtual NODE NODE { get; set; }
        public virtual NODE NODE1 { get; set; }
    }
}
