//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsArch.NET.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXTERNAL_CONFIG
    {
        public int ID_ATTR { get; set; }
        public int ID_TYPE { get; set; }
        public string STR_LABEL { get; set; }
        public bool UNIQUE_LINK { get; set; }
        public bool TREE_SEARCH { get; set; }
        public bool ATTRS_SEARCH { get; set; }
        public string STR_TYPES { get; set; }
        public string STR_ATTRS { get; set; }
        public string STR_STARTTYPE { get; set; }
        public string STR_STARTLABEL { get; set; }
        public string STR_RESATTRS { get; set; }
    
        public virtual ATTR ATTR { get; set; }
    }
}
