//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsArch.NET.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAVOURITES_TREE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FAVOURITES_TREE()
        {
            this.FAVOURITES_TREE1 = new HashSet<FAVOURITES_TREE>();
        }
    
        public int ID_FAV { get; set; }
        public int ID_USER { get; set; }
        public Nullable<int> ID_NODE { get; set; }
        public Nullable<int> ID_PARENT { get; set; }
        public string STR_LABEL { get; set; }
        public Nullable<int> N_ORDER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAVOURITES_TREE> FAVOURITES_TREE1 { get; set; }
        public virtual FAVOURITES_TREE FAVOURITES_TREE2 { get; set; }
        public virtual NODE NODE { get; set; }
        public virtual USER USER { get; set; }
    }
}
