//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsArch.NET.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORY_EVENTS
    {
        public int ID_NODE { get; set; }
        public Nullable<int> ID_ATTR { get; set; }
        public Nullable<int> ID_COL { get; set; }
        public Nullable<int> N_ORDER { get; set; }
        public Nullable<double> FLOATVALUE_OLD { get; set; }
        public Nullable<double> FLOATVALUE_NEW { get; set; }
        public Nullable<System.DateTime> DATEVALUE_OLD { get; set; }
        public Nullable<System.DateTime> DATEVALUE_NEW { get; set; }
        public string TEXTVALUE_OLD { get; set; }
        public string TEXTVALUE_NEW { get; set; }
        public Nullable<int> ID_REFNODE { get; set; }
        public int ID_KEY { get; set; }
        public byte[] IMAGEVALUE_OLD { get; set; }
        public byte[] IMAGEVALUE_NEW { get; set; }
    }
}
