//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsArch.NET.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORY_TYPES
    {
        public int ID_ITEMTYPE { get; set; }
        public int ID_REFTYPE { get; set; }
        public int ID_DEFNODE { get; set; }
        public int ID_KEY { get; set; }
    }
}
