//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsArch.NET.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPORTNODE
    {
        public int ID_NODE { get; set; }
        public Nullable<int> ID_DICTATTR { get; set; }
        public string STR_DICTVALUE { get; set; }
        public int ID_IMPORTNODE { get; set; }
        public int ID_KEY { get; set; }
    }
}
