//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsArch.NET.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMPORTSETTING
    {
        public int ID_SET { get; set; }
        public Nullable<int> ID_TYPE { get; set; }
        public Nullable<int> ID_HISTTYPE { get; set; }
        public Nullable<bool> IS_FULLEXPORT { get; set; }
        public Nullable<bool> IS_ORGUSER { get; set; }
        public Nullable<int> ID_ATTR { get; set; }
        public Nullable<int> ID_PARENTTYPE { get; set; }
        public Nullable<int> ID_PARENTATTR { get; set; }
    }
}
