//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsArch.NET.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEMTYPE_REF
    {
        public int ID_ITEMTYPE1 { get; set; }
        public int ID_ITEMTYPE2 { get; set; }
        public bool REF_MASK { get; set; }
    
        public virtual ITEMTYPE ITEMTYPE { get; set; }
        public virtual ITEMTYPE ITEMTYPE1 { get; set; }
    }
}
