//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsArch.NET.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEMTYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ITEMTYPE()
        {
            this.CHILD_ATTRS = new HashSet<CHILD_ATTRS>();
            this.CHILD_USER_ATTRS = new HashSet<CHILD_USER_ATTRS>();
            this.EVENTRULE_OBJECTS = new HashSet<EVENTRULE_OBJECTS>();
            this.EVENTS = new HashSet<EVENT>();
            this.EXTERNAL_CHILD_ATTRS = new HashSet<EXTERNAL_CHILD_ATTRS>();
            this.ITEMTYPE_REF = new HashSet<ITEMTYPE_REF>();
            this.ITEMTYPE_REF1 = new HashSet<ITEMTYPE_REF>();
            this.NODEs = new HashSet<NODE>();
            this.ROLE_FORMS = new HashSet<ROLE_FORMS>();
            this.SEARCH_TABLES = new HashSet<SEARCH_TABLES>();
            this.TREE_ATTRS = new HashSet<TREE_ATTRS>();
            this.TREE_CONFIG = new HashSet<TREE_CONFIG>();
            this.TYPE_ATTR = new HashSet<TYPE_ATTR>();
            this.VIRTUAL_ATTRS = new HashSet<VIRTUAL_ATTRS>();
            this.USERS = new HashSet<USER>();
        }
    
        public int ID { get; set; }
        public string STR_NAME { get; set; }
        public byte[] ICON { get; set; }
        public int FILE_TYPE { get; set; }
        public byte[] ICONFILE { get; set; }
        public byte[] ICONSEL { get; set; }
        public byte[] ICONNOFILE { get; set; }
        public byte[] ICONIMAGE { get; set; }
        public byte[] ICONFILEIMAGE { get; set; }
        public Nullable<bool> B_NOTNAV { get; set; }
        public Nullable<int> N_ORDER { get; set; }
        public string FORM_XML { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHILD_ATTRS> CHILD_ATTRS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHILD_USER_ATTRS> CHILD_USER_ATTRS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVENTRULE_OBJECTS> EVENTRULE_OBJECTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EVENT> EVENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXTERNAL_CHILD_ATTRS> EXTERNAL_CHILD_ATTRS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITEMTYPE_REF> ITEMTYPE_REF { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITEMTYPE_REF> ITEMTYPE_REF1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NODE> NODEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ROLE_FORMS> ROLE_FORMS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEARCH_TABLES> SEARCH_TABLES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TREE_ATTRS> TREE_ATTRS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TREE_CONFIG> TREE_CONFIG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TYPE_ATTR> TYPE_ATTR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VIRTUAL_ATTRS> VIRTUAL_ATTRS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER> USERS { get; set; }
    }
}
