//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsArch.NET.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEMTYPES_TREE
    {
        public int ID_KEY { get; set; }
        public Nullable<int> ID_PARENT { get; set; }
        public Nullable<int> ID_ITEMTYPE { get; set; }
        public string STR_LABEL { get; set; }
        public Nullable<int> ID_ATTR { get; set; }
        public Nullable<bool> IS_FOLDER { get; set; }
        public Nullable<int> N_ORDER { get; set; }
    }
}
