//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsArch.NET.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NAV_BUTTONS
    {
        public int ID_BUTTON { get; set; }
        public int ID_ITEMTYPE { get; set; }
        public string STR_HINT { get; set; }
        public Nullable<bool> B_VISIBLE { get; set; }
    }
}
