//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsArch.NET.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NODE_GROUP
    {
        public int ID_NODE { get; set; }
        public int ID_GROUP { get; set; }
        public Nullable<int> N_RIGHTS { get; set; }
    
        public virtual GROUP GROUP { get; set; }
        public virtual NODE NODE { get; set; }
    }
}
