//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsArch.NET.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NODE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NODE()
        {
            this.ATTRVAL_CHAR = new HashSet<ATTRVAL_CHAR>();
            this.ATTRVAL_DATE = new HashSet<ATTRVAL_DATE>();
            this.ATTRVAL_FLOAT = new HashSet<ATTRVAL_FLOAT>();
            this.ATTRVAL_IMAGE = new HashSet<ATTRVAL_IMAGE>();
            this.ATTRVAL_INT = new HashSet<ATTRVAL_INT>();
            this.ATTRVAL_LV = new HashSet<ATTRVAL_LV>();
            this.ATTRVAL_TEXT = new HashSet<ATTRVAL_TEXT>();
            this.EXTERNAL_LINKS = new HashSet<EXTERNAL_LINKS>();
            this.EXTERNAL_LINKS1 = new HashSet<EXTERNAL_LINKS>();
            this.FAVOURITES_TREE = new HashSet<FAVOURITES_TREE>();
            this.FILESCONFIG_NODE = new HashSet<FILESCONFIG_NODE>();
            this.NODE_GROUP = new HashSet<NODE_GROUP>();
            this.NODE1 = new HashSet<NODE>();
            this.REFATTRS = new HashSet<REFATTR>();
            this.REFATTRS1 = new HashSet<REFATTR>();
            this.REFATTRS_USER = new HashSet<REFATTRS_USER>();
            this.STORAGEs = new HashSet<STORAGE>();
            this.TABLEVAL_CHAR = new HashSet<TABLEVAL_CHAR>();
            this.TABLEVAL_DATE = new HashSet<TABLEVAL_DATE>();
            this.TABLEVAL_FLOAT = new HashSet<TABLEVAL_FLOAT>();
            this.TABLEVAL_INT = new HashSet<TABLEVAL_INT>();
            this.USER_FILES = new HashSet<USER_FILES>();
            this.ATTRS = new HashSet<ATTR>();
            this.USERS = new HashSet<USER>();
        }
    
        public int ID_NODE { get; set; }
        public Nullable<int> ID_PARENT { get; set; }
        public int ID_ITEMTYPE { get; set; }
        public int N_ORDER { get; set; }
        public string STR_LABEL { get; set; }
        public Nullable<System.DateTime> DATE_LAST { get; set; }
        public Nullable<System.DateTime> DATE_CREATE { get; set; }
        public int ID_USER { get; set; }
        public Nullable<int> ID_OLDPARENT { get; set; }
        public Nullable<int> N_MODE { get; set; }
        public int LINK_COUNTER { get; set; }
        public Nullable<System.DateTime> DATE_MODIFY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTRVAL_CHAR> ATTRVAL_CHAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTRVAL_DATE> ATTRVAL_DATE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTRVAL_FLOAT> ATTRVAL_FLOAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTRVAL_IMAGE> ATTRVAL_IMAGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTRVAL_INT> ATTRVAL_INT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTRVAL_LV> ATTRVAL_LV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTRVAL_TEXT> ATTRVAL_TEXT { get; set; }
        public virtual EXTERNAL_DB EXTERNAL_DB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXTERNAL_LINKS> EXTERNAL_LINKS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXTERNAL_LINKS> EXTERNAL_LINKS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAVOURITES_TREE> FAVOURITES_TREE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FILESCONFIG_NODE> FILESCONFIG_NODE { get; set; }
        public virtual ITEMTYPE ITEMTYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NODE_GROUP> NODE_GROUP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NODE> NODE1 { get; set; }
        public virtual NODE NODE2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REFATTR> REFATTRS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REFATTR> REFATTRS1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REFATTRS_USER> REFATTRS_USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<STORAGE> STORAGEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TABLEVAL_CHAR> TABLEVAL_CHAR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TABLEVAL_DATE> TABLEVAL_DATE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TABLEVAL_FLOAT> TABLEVAL_FLOAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TABLEVAL_INT> TABLEVAL_INT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_FILES> USER_FILES { get; set; }
        public virtual USER USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ATTR> ATTRS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER> USERS { get; set; }
    }
}
