//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsArch.NET.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPTION
    {
        public int ID { get; set; }
        public byte[] B_OPTIONS { get; set; }
        public Nullable<int> INT_VAL1 { get; set; }
        public Nullable<int> INT_VAL2 { get; set; }
        public Nullable<int> INT_VAL3 { get; set; }
        public string STR_VAL1 { get; set; }
        public string STR_VAL2 { get; set; }
        public string MENU_XML { get; set; }
    }
}
