//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsArch.NET.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUERy
    {
        public int ID_QUERY { get; set; }
        public string TEXT_QUERY { get; set; }
        public string SQL_QUERY { get; set; }
        public string STR_NAME { get; set; }
    }
}
