//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsArch.NET.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUERY_USER
    {
        public int ID_QUERY { get; set; }
        public int ID_USER { get; set; }
        public int ID_TYPE { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
