//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsArch.NET.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class repl_node
    {
        public int id_node { get; set; }
        public Nullable<int> id_replnode { get; set; }
        public int is_cardchange { get; set; }
        public int is_filechange { get; set; }
        public System.DateTime change_time { get; set; }
        public System.DateTime repl_time { get; set; }
    }
}
