//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsArch.NET.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLE_CONTROLS_CONDITION
    {
        public int ID_ROLE { get; set; }
        public string STR_NAME { get; set; }
        public int ID_FUN { get; set; }
        public int N_ORDER { get; set; }
        public string STR_COND { get; set; }
        public string STR_VALUE { get; set; }
        public int ID_TYPE { get; set; }
        public int OP_COND { get; set; }
    }
}
