//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsArch.NET.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLE_DATA_IMAGES
    {
        public int ID_ROLE { get; set; }
        public int ID_IMAGE { get; set; }
        public Nullable<int> ID_TYPE { get; set; }
        public byte[] IMAGE_FILE { get; set; }
    }
}
