//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsArch.NET.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLE_CONTROLS_XML
    {
        public int ID_ROLE { get; set; }
        public int ID_TYPE { get; set; }
        public string STR_NAME { get; set; }
        public int ID_ATTR { get; set; }
        public int IS_DEFAULT { get; set; }
    }
}
