//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsArch.NET.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLE_FORMS
    {
        public int ID_ROLE { get; set; }
        public int ID_ITEMTYPE { get; set; }
        public string FORM_XML { get; set; }
    
        public virtual ITEMTYPE ITEMTYPE { get; set; }
        public virtual ROLE ROLE { get; set; }
    }
}
