//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsArch.NET.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEARCHTABLE_CONDS
    {
        public int ID_ATTR { get; set; }
        public int ID_COL { get; set; }
        public Nullable<int> COL_SEARCH { get; set; }
        public string STR_VALUE { get; set; }
    }
}
