//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsArch.NET.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECURITY_LOG
    {
        public int ID { get; set; }
        public int CAT { get; set; }
        public System.DateTime LOG_TIME { get; set; }
        public string HOST { get; set; }
        public Nullable<int> AIP_USER { get; set; }
        public string MSG { get; set; }
        public Nullable<int> RIGHT_ID { get; set; }
        public Nullable<int> PERMISSION_ID { get; set; }
        public Nullable<int> NODE_ID { get; set; }
        public Nullable<int> EVENT_ID { get; set; }
    }
}
