//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsArch.NET.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATUSBAR
    {
        public int ID_ITEMTYPE { get; set; }
        public int N_POS { get; set; }
        public int N_PANEL { get; set; }
        public Nullable<int> INT_WIDTH { get; set; }
        public string STR_TEXT { get; set; }
    }
}
