//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsArch.NET.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class STORAGE
    {
        public int ID_NODE { get; set; }
        public string STR_DOCFILE { get; set; }
        public int N_ORDER { get; set; }
        public Nullable<System.DateTime> EDIT_TIME { get; set; }
    
        public virtual NODE NODE { get; set; }
    }
}
