//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsArch.NET.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEM_REPLICCONFIG
    {
        public int cfgId { get; set; }
        public string cfgTag { get; set; }
        public string cfgCharValue { get; set; }
        public Nullable<int> cfgIntValue { get; set; }
    }
}
