//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsArch.NET.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SYSTEM_REPLICATIONCHECK
    {
        public int nodeId { get; set; }
        public string regionId { get; set; }
        public Nullable<int> nodeItemtype { get; set; }
        public Nullable<int> nodeParent { get; set; }
        public Nullable<int> nodeModifyFlag { get; set; }
        public Nullable<System.DateTime> nodeLastModify { get; set; }
        public Nullable<System.DateTime> nodeDispatched { get; set; }
    }
}
