//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsArch.NET.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLECONFIG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TABLECONFIG()
        {
            this.TABLE_SORTING = new HashSet<TABLE_SORTING>();
        }
    
        public int ID_ATTR { get; set; }
        public int ID_COL { get; set; }
        public string STR_NAME { get; set; }
        public int COLTYPE { get; set; }
        public Nullable<int> INT_FROM { get; set; }
        public Nullable<int> INT_TO { get; set; }
        public Nullable<int> INT_WIDTH { get; set; }
        public string STR_FORMUL { get; set; }
    
        public virtual ATTR ATTR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TABLE_SORTING> TABLE_SORTING { get; set; }
    }
}
