//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsArch.NET.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLELISTCONFIG
    {
        public string STR_NAME { get; set; }
        public int ID_ATTR { get; set; }
        public int ID_COL { get; set; }
        public int ID_DICT { get; set; }
        public Nullable<int> ID_PARENT { get; set; }
        public string STR_LABEL { get; set; }
        public Nullable<int> N_ORDER { get; set; }
    
        public virtual ATTR ATTR { get; set; }
    }
}
