//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsArch.NET.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TYPE_ATTR
    {
        public int ID_TYPE { get; set; }
        public int ID_ATTR { get; set; }
        public Nullable<int> OPTIONS { get; set; }
        public Nullable<int> N_ORDER { get; set; }
    
        public virtual ATTR ATTR { get; set; }
        public virtual ITEMTYPE ITEMTYPE { get; set; }
    }
}
