//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsArch.NET.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.FAVOURITES_TREE = new HashSet<FAVOURITES_TREE>();
            this.NODEs = new HashSet<NODE>();
            this.QUERY_USER = new HashSet<QUERY_USER>();
            this.REFATTRS_USER = new HashSet<REFATTRS_USER>();
            this.USER_FILES = new HashSet<USER_FILES>();
            this.NODEs1 = new HashSet<NODE>();
            this.ITEMTYPES = new HashSet<ITEMTYPE>();
            this.ROLES = new HashSet<ROLE>();
            this.GROUPS = new HashSet<GROUP>();
        }
    
        public int ID_USER { get; set; }
        public string STR_LOGIN { get; set; }
        public byte[] BIN_PASSWORD { get; set; }
        public bool B_DISABLED { get; set; }
        public string DESCRIPTION { get; set; }
        public string FULL_NAME { get; set; }
        public string SECONDARY_NAME { get; set; }
        public string GIVEN_NAME { get; set; }
        public Nullable<System.DateTime> WHEN_CREATED { get; set; }
        public Nullable<System.DateTime> WHEN_CHANGED { get; set; }
        public Nullable<System.DateTime> WHEN_EXPIRES { get; set; }
        public string MAIL { get; set; }
        public string PERSONAL_PHONE { get; set; }
        public string WORK_PHONE { get; set; }
        public string JOB_TITLE { get; set; }
        public Nullable<int> SEX { get; set; }
        public Nullable<System.DateTime> BIRTH_DAY { get; set; }
        public string ADMINISTRATOR_NOTE { get; set; }
        public Nullable<bool> ACTIVE_DIRECTORY { get; set; }
        public string PATRONYMIC_NAME { get; set; }
        public byte[] IMAGE_USER { get; set; }
        public Nullable<int> ATTEMPTS_QUANTITY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAVOURITES_TREE> FAVOURITES_TREE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NODE> NODEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QUERY_USER> QUERY_USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REFATTRS_USER> REFATTRS_USER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_FILES> USER_FILES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NODE> NODEs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITEMTYPE> ITEMTYPES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ROLE> ROLES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GROUP> GROUPS { get; set; }
    }
}
