//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsArch.NET.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_CONFIG
    {
        public int ID_USER { get; set; }
        public Nullable<bool> B_TREE { get; set; }
        public Nullable<bool> B_SEARCHPANEL { get; set; }
        public Nullable<bool> B_NAVPANEL { get; set; }
        public Nullable<bool> B_LIST { get; set; }
        public Nullable<int> ID_NODE { get; set; }
        public string XML_CONFIG { get; set; }
        public string XML_CONFIGTOOLBAR { get; set; }
        public Nullable<int> ID_START_NODE { get; set; }
        public string XML_IMPORT_CONFIG { get; set; }
    }
}
