//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsArch.NET.EntityDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIRTUAL_ATTRS
    {
        public int ID_ATTR { get; set; }
        public Nullable<int> ID_FUNATTR { get; set; }
        public Nullable<int> ID_COL { get; set; }
        public Nullable<int> ID_FUN { get; set; }
        public string STR_CONCAT { get; set; }
        public int ID_KEY { get; set; }
        public Nullable<int> ID_TYPE { get; set; }
    
        public virtual ITEMTYPE ITEMTYPE { get; set; }
    }
}
